### ISSUE TITLE
Yett lib is throwing errors when trying to test it using WASP plugin

### ISSUE THREAD

**Issue by rohitreddy0109** [snipsco/yett#14]
Team,

I am using WASP which is a chrome extension which will give a visual representation of all the tags and scripts loaded into DOM. When I try to test yett library using WASP plugin it throws js errors on the page load after clicking on "WASP" in chrome dev tools. I have tested it using yett demo app and with my custom app as well and its the same issue. Below is the error:

`monkey.js:16 Uncaught TypeError: Cannot redefine property: src
    at Function.defineProperties (<anonymous>)
    at HTMLDocument.document.createElement (monkey.js:16)
    at (index):21
    at (index):25`

Attached are the screen shots of the same
<img width="1680" alt="yett_console_error" src="https://user-images.githubusercontent.com/4636895/68245834-ddbfe080-ffd4-11e9-97ba-fdbe6f7e552d.png">
<img width="1680" alt="yett_script_error" src="https://user-images.githubusercontent.com/4636895/68245951-1f508b80-ffd5-11e9-9e1b-65683bf175e8.png">

**Comment by rohitreddy0109** [comment]
WASP Url: https://chrome.google.com/webstore/detail/waspinspector-analytics-s/niaoghengfohplclhbjnjheodgkejpih?hl=en

**Comment by rohitreddy0109** [comment]
Can someone please provide an update on the above issue ?

**Comment by elbywan** [comment]
Hi @rohitreddy0109,

I tried with the extension, but I did not get any errors on the demo website.

<img width="1433" alt="Capture d’écran 2019-11-08 à 08 40 21" src="https://user-images.githubusercontent.com/3428394/68458633-92d7e000-0203-11ea-838a-4e5aaab924fe.png">

**Comment by rohitreddy0109** [comment]
> Hi @rohitreddy0109,
> 
> > When I try to test yett library using WASP plugin it throws js errors on the page load after clicking on "WASP" in chrome dev tools.
> 
> I tried browsing the demo website with the extension enabled, but did not get any errors.
> 
> <img alt="Capture d’écran 2019-11-08 à 08 40 21" width="1433" src="https://user-images.githubusercontent.com/3428394/68458633-92d7e000-0203-11ea-838a-4e5aaab924fe.png">
> 
> We try to keep yett as compatible as possible, but in this case WASP seems to be closed source so there's not way to exactly know how they are tampering with the script tags in the page, especially if I cannot reproduce the issue.
> 
> Could you try to fix it on your side and make a PR?

Hi @elbywan,
I am able to reproduce the issue. Once you load the WASP plugin, please try to refresh the page again and/or click on try again button, then you will see the console errors in dev tools.

The issue is WASP plugin is trying to create a "script" element using object.defineProperty with configurable as false for 'src' property and yett lib is again trying to create the "script" element using the object.defineProperties and then its throwing an error saying "cannot redefine property src' since the configurable is false. 

The way to fix this is not to create the "script" element again with src property if its already present in the DOM. I can quickly raise a PR for this fix ?

Attached is the screen shot of the script  of the wasp plugin, which is creating this script.
![WASP plugin error](https://user-images.githubusercontent.com/4636895/68684760-443d8500-0526-11ea-85e9-dcd83815eb38.png)

**Comment by elbywan** [comment]
@rohitreddy0109 Sorry for the delay,

> The issue is WASP plugin is trying to create a "script" element using object.defineProperty with default value as "false" for "configurable" in 'src' property of the object and yett lib is again trying to create the "script" element using the object.defineProperties and then its throwing an error saying "cannot redefine property src' since the configurable is false.

I think that the issue is more likely to be caused because this plugin monkey patches the `document.createElement`. When some code tries to programmatically create a script tag, the plugin locks the src element before yett's monkey patched function is called and crashes. 

This means that `yett` and `WASP` will never be compatible. But I released a new version that should at least not prevent script creation, but instead display a warning in the console.

I also added a small warning paragraph in the readme.
