### ISSUE TITLE
add a block option ? to have a complete light consent manager ?

### ISSUE THREAD

**Issue by sede1971** [snipsco/yett#17]
With GDPR EU law, user can be choice between cookies or cookies categories which cookie he wants to activate.
one new option to block again if user modify his choices will be nice

I see this fork https://github.com/oondeo/yett
it seems that a new block function has created in this git
what do you think of these changes ?

**Comment by elbywan** [comment]
Hi @sede1971,

> one new option to block again if user modify his choices will be nice

It is impossible to block a script that has already been executed.

**Comment by sede1971** [comment]
ok on my site I have placed a link in footer "my cookies" to display again the banner and I check if cookie is already settled with specific value, if it's the case, I reload the page to block again balcklisted scripts
You are right, one page reload it's the solution
