### ISSUE TITLE
Demo page does not block tracking scripts

### ISSUE THREAD

**Issue by noleakseu** [snipsco/yett#18]
.. and violates GDPR.
![Screenshot from 2020-02-25 16-34-38](https://user-images.githubusercontent.com/53650748/75262774-497cc200-57ed-11ea-8f1e-3457508a0b7e.png)

**Comment by elbywan** [comment]
@noleakseu It does not block **all** scripts, google analytics is whitelisted which is a choice made by the company running the website.

If you click `customize`, you can notice that is set to `enabled` by default and you have the option to block it.

<img width="846" alt="Capture d’écran 2020-02-25 à 16 42 42" src="https://user-images.githubusercontent.com/58975389/75263133-dd4e8e00-57ed-11ea-9f93-c8dec7202249.png">
