### ISSUE TITLE
Block these scripts when non essential toggle is off

### ISSUE THREAD

**Issue by sharanp98** [snipsco/yett#22]
I am trying to block a set of tracker scripts. The issue is I cannot figure out where the scripts are from, the domain name of these scripts. I could block google analytics by adding this in the blacklist:
  [/www\.googletagmanager\.com\/gtag\/js/,
  /google-analytics\.com/,
  /googletagmanager/,]

These are the other scripts I am trying to block. Could you help with where to find the domain name for these scripts:
- [ ]  Facebook Pixel
- [ ]  Google Tag Manager
- [ ]  Hotjar Analytics
- [ ]  Google Publisher Tag
- [ ]  Youtube embed
- [ ]  Vimeo embed
- [ ]  Google maps
- [ ]  Addthis widget
- [ ]  Sharethis widget
- [ ]  Twitter widget
- [ ]  Soundcloud embed
- [ ]  Slideshare embed
- [ ]  Linkedin widget
- [ ]  Instagram embed
- [ ]  Pinterest widget

**Comment by elbywan** [comment]
Hi @sharanp98,

> Could you help with where to find the domain name for these scripts:

I'm not sure this is the right place to ask and I cannot help you about your issue.

I suppose that these services have guides or instructions that you could have a look at, or you could monitor from your web browser network tab the domains from where the scripts are downloaded.
