### ISSUE TITLE
block google tag manager

### ISSUE THREAD

**Issue by militote** [snipsco/yett#3]
Hello Sr.

How to block google tag manager code?

**Comment by pocketjoso** [comment]
Hi,
You can follow [the small example in the readme](https://github.com/snipsco/yett#small-example).

Just replace `/my-blacklisted-domain/` with a regex that matches the url the google tag manager code loads from. It could be something like `/googletagmanager\.com/` - but please check this on your own - I am not using their service so I don't know the exact url.
