### ISSUE TITLE
[feature request] White-list patterns

### ISSUE THREAD

**Issue by dolav** [snipsco/yett#5]
My idea is to define a **YETT_WHITELIST** that let the users control sources they are trust to be executed (first-party scripts) when blocks all the others.
This way, unlock('some source') will add this source into YETT_WHITELIST and unlock() will allow everything.
Thanks for considering it.

**Comment by elbywan** [comment]
Hi @dolav, sorry for the delay!

I just pushed a new release that allows having a whitelist the way you suggested.
Hope this will suit your needs!

**Comment by dolav** [comment]
Thanks guys! :1st_place_medal:
