### ISSUE TITLE
Publish updates to npm

### ISSUE THREAD

**Issue by polarbirke** [snipsco/yett#58]
Hi @elbywan, 

I saw that you have diligently merged dependabot Updates – thank you for that! It feels good to see that this project is alive. ☺️ 

What I'm unsure about is whether the updates should be published to npm; the last version there is 0.2.3 (Published 3 years ago).

**Comment by elbywan** [comment]
Hey @polarbirke,

> What I'm unsure about is whether the updates should be published to npm

The updated packages are all devDependencies, `yett` is self contained and [does not use any other library at runtime](https://github.com/elbywan/yett/blob/master/package.json#L43).

So there should be no need to publish a new version.

**Comment by polarbirke** [comment]
Excellent, thank you for getting back so quickly!
