### ISSUE TITLE
How do you give the option of blocking the scripts again?

### ISSUE THREAD

**Issue by missusmy** [snipsco/yett#9]
GDPR now requires that you give the option of accessing your choices (accept or deny) so you can change your mind.

**Comment by elbywan** [comment]
Hi @missusmy,

Yett is a library that can be used to blocks third party scripts from **executing** (often at page loading time).

I'm not sure I fully understand what you're asking for, but if your question is about how to use yett to block scripts after having called the `unblock()` function then:
- The scripts will already be executing at that point.
- Yett is not meant to kill running scripts!

On the other hand, you could remember the user choice using a cookie (or store it on your backend, or use the local storage…) and refresh the page. And `yett` could then unblock based on the user preference.

But that is outside the scope of this library 😉.

**Comment by missusmy** [comment]
That's a good idea, thanks!
